name: Update Helm Values

# Triggered when repo1,2,3 dispatch events
on:
  repository_dispatch:
    types: [update-monolith, update-scan, update-storage]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update values.yaml
        run: |
          TYPE="${{ github.event.action || github.event.client_payload.type }}"
          TAG="${{ github.event.client_payload.tag }}"
          
          if [[ "${{ github.event.event_type }}" == "update-monolith" ]]; then
            sed -i '' "s|monolith:.*|monolith:\n  image: ghcr.io/${{ github.repository_owner }}/monolith-app\n  tag: ${TAG}|" values.yaml
          elif [[ "${{ github.event.event_type }}" == "update-scan" ]]; then
            sed -i '' "s|scan:.*|scan:\n  image: ghcr.io/${{ github.repository_owner }}/scan-service\n  tag: ${TAG}|" values.yaml
          elif [[ "${{ github.event.event_type }}" == "update-storage" ]]; then
            sed -i '' "s|storage:.*|storage:\n  image: ghcr.io/${{ github.repository_owner }}/storage-service\n  tag: ${TAG}|" values.yaml
          fi

      - name: Commit updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update Helm chart image tag from ${{ github.event.event_type }}" || echo "No changes"
          git push

      - name: Helm Lint
        run: |
          helm lint .
