name: Update Helm Values

permissions:
  contents: write
# Triggered when repo1,2,3 dispatch events
on:
  repository_dispatch:
    types: [update-monolith, update-scan, update-storage]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Update values.yaml
        run: |
          TYPE="${{ github.event.client_payload.type }}"
          TAG="${{ github.event.client_payload.tag }}"
          ORG="${{ github.repository_owner }}"

          case "${TYPE}" in
            update-monolith)
              yq -i -y '.monolith.image = "ghcr.io/'"$ORG"'/monolith-app"' values.yaml
              yq -i -y '.monolith.tag = "'$TAG'"' values.yaml
              ;;
            update-scan)
              yq -i -y '.scan.image = "ghcr.io/'"$ORG"'/scan-service"' values.yaml
              yq -i -y '.scan.tag = "'$TAG'"' values.yaml
              ;;
            update-storage)
              yq -i -y '.storage.image = "ghcr.io/'"$ORG"'/storage-service"' values.yaml
              yq -i -y '.storage.tag = "'$TAG'"' values.yaml
              ;;
            *)
              echo "Unknown event type: ${TYPE}"
              exit 1
              ;;
          esac

      - name: Show updated values.yaml
        run: cat values.yaml

      - name: Commit and push
        run: |
          git config user.name "bathinamahesh"
          git config user.email "bathinamahesh5399game@gmail.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add values.yaml
            git commit -m "Update Helm chart image tag from ${{ github.event.event_type }}"
            # Update remote to use token for authentication
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository_owner }}/polycloud-helm.git
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Helm Lint
        run: |
          helm lint .
