name: Update Helm Values

# Triggered when repo1,2,3 dispatch events
on:
  repository_dispatch:
    types: [update-monolith, update-scan, update-storage]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Update values.yaml
        run: |
          TYPE="${{ github.event.client_payload.type }}"
          TAG="${{ github.event.client_payload.tag }}"
          ORG="${{ github.repository_owner }}"

          case "${TYPE}" in
            update-monolith)
              yq e -i '.monolith.image = "ghcr.io/'"$ORG"'/monolith-app"' values.yaml
              yq e -i '.monolith.tag = "'$TAG'"' values.yaml
              ;;
            update-scan)
              yq e -i '.scan.image = "ghcr.io/'"$ORG"'/scan-service"' values.yaml
              yq e -i '.scan.tag = "'$TAG'"' values.yaml
              ;;
            update-storage)
              yq e -i '.storage.image = "ghcr.io/'"$ORG"'/storage-service"' values.yaml
              yq e -i '.storage.tag = "'$TAG'"' values.yaml
              ;;
            *)
              echo "Unknown event type: ${TYPE}"
              exit 1
              ;;
          esac

      - name: Show updated values.yaml
        run: cat values.yaml

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add values.yaml
            git commit -m "Update Helm chart image tag from ${{ github.event.event_type }}"
            git remote set-url origin https://$GH_PAT@github.com/${{ github.repository_owner }}/polycloud-helm.git
            git push origin HEAD:main
          fi

      - name: Helm Lint
        run: |
          helm lint .
